//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.09.08 at 05:16:10 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://kasource.org/schema/nats/test/person", location = "src/test/resources/xml/person.xsd")
package org.kasource.spring.nats.integration.xml;
